#!/bin/bash

# nicely formatted diff
batdiff() {
  git diff --name-only --diff-filter=d $@ | xargs bat --diff
}


# autocd while using ranger
ranger_cd() {
	temp_file="$(mktemp -t "ranger_cd.XXXXXXXXXX")"
	ranger --choosedir="$temp_file" -- "${@:-$PWD}"
	if chosen_dir="$(cat -- "$temp_file")" && [ -n "$chosen_dir" ] && [ "$chosen_dir" != "$PWD" ]; then
		cd -- "$chosen_dir"
	fi
	rm -f -- "$temp_file" > /dev/null
}
