#!/bin/sh

# sane defaults
alias \
      cp="cp -iv" \
      mv="mv -iv" \
      rm="rm -vi" \
      rd="rmdir -pv" \
      rmrf="rm -rf" \
      mkdir="mkdir -pv" \
      yt="yt-dlp" \
      yta="yt-dlp -x -f bestaudio/best"


# colorizing
alias \
      ls="ls --color --classify --human-readable --quoting-style=escape" \
      ll="ls -lhA --color=auto --group-directories-first" \
      l="eza -a --color=always --group-directories-first --classify --icons" \
      grep="grep --color=auto" \
      diff="diff --color=auto"

# git aliases
alias \
      g='_f() { if [[ $# == 0 ]]; then git status -sb; else git "$@"; fi }; _f' \
      ga="git add" \
      gd="git diff" \
      gp="git push" \
      gc="git commit" \
      gcl="git clone" \
      gst="git status" \
      gpl="git pull" \
      gch="git checkout" \
      gcb="git checkout -b" \
      gcm="git checkout main" \
      gcd="git checkout develop" \
      glg="git log --oneline" \
      glgg="git log --oneline --graph" \
      glgga="git log --oneline --graph --all" \
      gcmsg="git commit -m"

# tmux aliases
alias \
      tn="tmux new -s $(basename $(pwd))" \
      ta="tmux attach"

# fzf aliases
alias \
      ffe="fzf_find_edit" \
      fcd="fzf_change_directory" \
      fkill="fzf_kill" \
      gadd="fzf_git_add" \
      pin="pacman -Slq | fzf --multi --preview 'pacman -Si {1}' | xargs -ro doas pacman -S" \
      prm="pacman -Qq | fzf --multi --preview 'pacman -Qi {1}' | xargs -ro doas pacman -Rns"

# other aliases
alias \
      e="emacs" \
      v="nvim" \
      p="doas pacman" \
      z="zathura" \
      s="kitty +kitten ssh zeus@dissidentx.com" \
      ka="killall" \
      rg="rg --hidden --smart-case" \
      sx="startx ~/.config/x11/xinitrc" \
      cam="mpv av://v4l2:/dev/video0 --profile=low-latency --untimed" \
      sdn="shutdown -h now" \
      vis="export TERM=rxvt-256color && vis" \
      copy="xclip -i -selection clipboard" \
      word="shuf -n 1 $XDG_DATA_HOME/misc/new_words.txt" \
      words="bat $XDG_DATA_HOME/misc/new_words.txt" \
      audible="mpv --demuxer-lavf-o=activation_bytes=72830b37" \
      vpn="doas openconnect -u fdai7682 --authgroup=01\)_HS-Fulda-SSL-VPN vpn.rz.hs-fulda.de" \
      netlab_vpn="doas openconnect -u fdai7682 --authgroup=05\)_AI-NetLab-Pro vpn.rz.hs-fulda.de" \
