#!/bin/sh

# sane defaults
alias \
      cp="cp -iv" \
      mv="mv -iv" \
      rm="rm -vi" \
      rd="rmdir -pv" \
      rmrf="rm -rf" \
      mkdir="mkdir -pv" \
      yt="youtube-dl" \
      yta="yt -x -f bestaudio/best"


# colorizing
alias \
      ls="ls --color --classify --human-readable --quoting-style=escape" \
      ll="ls -lhA --color=auto --group-directories-first" \
      l="exa -a --color=always --group-directories-first --classify --icons" \
      grep="grep --color=auto" \
      diff="diff --color=auto"

# git aliases
alias \
      g='_f() { if [[ $# == 0 ]]; then git status -sb; else git "$@"; fi }; _f' \
      ga="git add" \
      gd="git diff" \
      gp="git push" \
      gc="git commit" \
      gcl="git clone" \
      gst="git status" \
      gpl="git pull" \
      gch="git checkout" \
      gcb="git checkout -b" \
      gcm="git checkout main" \
      gcd="git checkout develop" \
      glg="git log --oneline" \
      glgg="git log --oneline --graph" \
      glgga="git log --oneline --graph --all" \
      gcmsg="git commit -m"

# tmux aliases
alias \
      tn="tmux new -s $(basename $(pwd))" \
      ta="tmux attach"

# fzf aliases
alias \
      ffe="fzf_find_edit" \
      fcd="fzf_change_directory" \
      fkill="fzf_kill" \
      gadd="fzf_git_add"

# other aliases
alias \
      e="emacs" \
      v="nvim" \
      p="doas pacman" \
      h="history 0 | cut -c 8- | sort | uniq | fzf | tr '\\\n' ' ' | xclip -selection clipboard" \
      z="zathura" \
      ka="killall" \
      cam="mpv av://v4l2:/dev/video0 --profile=low-latency --untimed" \
      sdn="shutdown -h now" \
      copy="xclip -i -selection clipboard" \
      rcava="cava | lolcat" \
      word="shuf -n 1 $XDG_DATA_HOME/misc/new_words.txt" \
      words="bat $XDG_DATA_HOME/misc/new_words.txt" \
