#!/bin/sh

# nicely formatted diff
batdiff() {
  git diff --name-only --diff-filter=d $@ | xargs bat --diff
}

# using lf to change directories
lfcd () {
    tmp="$(mktemp)"
    lf -last-dir-path="$tmp" "$@"
    if [ -f "$tmp" ]; then
        dir="$(cat "$tmp")"
        rm -f "$tmp" >/dev/null
        [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
    fi
}
