#!/bin/sh

# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

rotate() {
    degree="$1"
    tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
    case "$(file -b -i "$file")" in
        image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
        *)           mogrify  -rotate "$degree" "$file" ;;
    esac
done
}

while read file
do
    case "$1" in
        "y")        xclip -selection clipboard -t image/png -i "$file" ;;
        "w")        setbg "$file" ;;
        "x")        rm "$file" ;;
        "C-comma")  rotate 270 ;;
        "C-period") rotate  90 ;;
        "C-slash")  rotate 180 ;;
    esac
done

