#! /bin/bash

# dual monitor setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

if [[ $(xrandr --query | grep 'HDMI-1 connected') ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1600x900 --rotate normal --left-of eDP-1
    bspc monitor HDMI-1 -d 1 2 3 4 5
    bspc monitor eDP-1 -d 6 7 8 9 0
else
    xrandr --output eDP-1 --auto --output HDMI-1 --off
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 0
fi

# alias functions
_(){ bspc config "$@"; }
R(){ bspc rule -a "$@"; }

# bspwm configuration
_ window_gap            8
_ border_width          2
_ split_ratio           0.6
_ borderless_monocle    true
_ gapless_monocle       true

# colors
_ active_border_color "#767c82"
_ focused_border_color "#767c82"

# rules
R feh state=floating

# wallpaper
feh --no-fehbg --bg-fill "$XDG_DATA_HOME/wallies/current_wallie.png" &

# polybar
"$HOME/.config/polybar/launch.sh"
