#! /bin/bash

# dual monitor setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 0


if [[ $(xrandr --query | grep 'HDMI1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --mode 1920x1080 --pos 1920x0 --rotate normal --output VIRTUAL1 --off
    bspc monitor eDP1 -d 1 2 3 4 5
    bspc monitor HDMI1 -d 6 7 8 9 0
else
    xrandr --output eDP1 --auto --output HDMI1 --off
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi

# alias functions
_(){ bspc config "$@"; }
R(){ bspc rule -a "$@"; }

# bspwm configuration
_ window_gap            10
_ border_width          2
_ split_ratio           0.6
_ borderless_monocle    true
_ gapless_monocle       true

# colors
_ active_border_color "#767c82"
_ focused_border_color "#767c82"

# wallpaper
setbg "$XDG_DATA_HOME/wallies/current_wallie.png"

# polybar
"$HOME/.config/polybar/launch.sh"
