#! /bin/bash

# dual monitor setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xrandr --output eDP1 --auto --output HDMI-1 --off
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0

# alias functions
_(){ bspc config "$@"; }
R(){ bspc rule -a "$@"; }

# bspwm configuration
_ window_gap            10
_ border_width          2
_ split_ratio           0.6
_ borderless_monocle    true
_ gapless_monocle       true

# colors
_ active_border_color "#767c82"
_ focused_border_color "#767c82"

# wallpaper
setbg "$XDG_DATA_HOME/wallies/current_wallie.png"

# polybar
"$HOME/.config/polybar/launch.sh"
